// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://senypvvtufeyzcwtwwve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbnlwdnZ0dWZleXpjd3R3d3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjQ0MzIsImV4cCI6MjA2MDY0MDQzMn0.ckXBYEyatrWX620fPbJNTC2MmnVWu67DHZUebWe9-_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);